OPTIONS (ERRORS=50)
LOAD DATA 
INFILE 'IMAGES_DATA_TABLE.ldr' "str '{EOL}'"
APPEND
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "IMAGES"
FIELDS TERMINATED BY'|'
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS ( 
"IMAGEID" ,
"IMAGETYPE" ,
"NAME" CHAR (64),
L_0 FILLER char,
"IMAGE" LOBFILE( L_0) TERMINATED BY EOF NULLIF L_0 = 'null')
